language: node_js
sudo: required
dist: trusty
env:
  - CLI_VERSION=latest
addons:  
  apt:
    packages:
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - liblttng-ust0
    - libcurl3
    - libssl1.0.0
    - libuuid1
    - libkrb5
    - zlib1g
    - libicu52
branches:
  only:
    - develop
    - stable
    - master
install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
  - npm install
script:
  - gulp